version: '2'
services:
    redis:
        image: redis
        container_name: redis
        ports: 
            - "6379:6379"
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        depends_on:
            - redis
   